### PR TITLE
Improve performance - lock once per page - not per word.

### PR DESCRIPTION
**Pull request by arcturusannamalai**
Improve performance - lock once per page - not per word.

### CODE REVIEW

**Comment by psankar** [comment]
Hi, Thanks for the PR. I am a bit occupied until the weekend. I will look into this during the weekend.

**Comment by arcturusannamalai** [comment]
@psankar - pls check

**Comment by psankar** [comment]
Hi @arcturusannamalai Thanks for the PR. Sorry for the delay as I got a bit busy with things in personal and professional lives. I have not measured the performance (or regressions) but I believe that it should work fine 👍

**Comment by arcturusannamalai** [comment]
Hope you are well nanba.. @psankar  :)

**Pull request merged**
